from __future__ import annotations

# ruff: noqa: F401

from tests.support.prior_train_cases import (
    test_evaluate_tab_foundry_run_supports_runs_without_best_checkpoint,
    test_tabfoundry_staged_nano_exact_matches_simple_prior_batch_loss,
    test_train_tabfoundry_simple_prior_accepts_plain_adamw,
    test_train_tabfoundry_simple_prior_allows_zero_grad_clip,
    test_train_tabfoundry_simple_prior_averages_task_loss_and_steps_per_batch,
    test_train_tabfoundry_simple_prior_matches_nanotabpfn_loss_for_one_batch,
    test_train_tabfoundry_simple_prior_retries_with_smaller_microbatches_on_oom,
    test_train_tabfoundry_simple_prior_saves_checkpoints_in_eval_mode,
    test_train_tabfoundry_simple_prior_skip_policy_preserves_successful_step_budget,
    test_train_tabfoundry_simple_prior_skips_non_finite_loss_steps,
    test_train_tabfoundry_staged_prior_writes_activation_norms_when_enabled,
    test_train_tabfoundry_staged_prior_writes_context_gradient_keys_when_active,
    test_train_tabfoundry_staged_prior_writes_staged_gradient_keys,
)
