from __future__ import annotations

# ruff: noqa: F401

from tests.support_research.system_delta_execute import (
    test_archive_incomplete_train_dir_moves_partial_history_aside,
    test_completed_train_artifacts_exist_accepts_exact_normalized_surface_match,
    test_completed_train_artifacts_exist_accepts_prior_dump_alias_for_legacy_prior,
    test_completed_train_artifacts_exist_accepts_stage_scoped_latest_checkpoint,
    test_completed_train_artifacts_exist_rejects_backend_mismatch,
    test_completed_train_artifacts_exist_rejects_manifest_identity_mismatch,
    test_completed_train_artifacts_exist_rejects_missing_backend_marker,
    test_completed_train_artifacts_exist_rejects_schedule_mismatch,
    test_completed_train_artifacts_exist_rejects_unsuccessful_telemetry,
    test_row_id_for_order_allocates_v2_for_reset_row_when_delta_root_has_historical_v1,
    test_row_id_for_order_counts_interrupted_versions_as_consumed,
    test_row_id_for_order_uses_highest_registry_version_when_filesystem_is_missing,
    test_resolve_training_backend_rejects_unsupported_source,
    test_run_row_archives_completed_but_incompatible_selected_train_dir_and_retrains,
    test_run_row_legacy_sweep_meta_ignores_synthetic_anchor_context_experiment,
    test_run_row_requires_prior_dump_for_legacy_prior_rows,
    test_run_row_reset_tf_rd_010_style_row_allocates_fresh_run_id_and_retrains,
    test_run_row_resolves_dynamic_post_stack_norm_from_screened_rows,
    test_run_row_screen_only_updates_queue_without_benchmark,
    test_run_row_uses_manifest_trainer_for_manifest_rows,
    test_run_row_uses_prior_dump_trainer_for_prior_dump_rows,
)
