from __future__ import annotations

# ruff: noqa: F401

from tests.support_research.system_delta_execute import (
    test_resolve_reusable_nanotabpfn_curve_allows_cross_device_reuse_on_the_same_host,
    test_resolve_reusable_nanotabpfn_curve_falls_back_to_control_baseline_when_anchor_is_unavailable,
    test_resolve_reusable_nanotabpfn_curve_matches_repo_tracked_bundle_across_checkouts,
    test_resolve_reusable_nanotabpfn_curve_rejects_legacy_summary_without_timing_metadata,
    test_resolve_reusable_nanotabpfn_curve_requires_host_fingerprint_match,
    test_resolve_reusable_nanotabpfn_curve_skips_missing_summary_or_curve,
    test_run_row_benchmark_full_reuses_anchor_curve_without_bootstrapping_nanotabpfn_env,
    test_run_row_benchmark_full_supports_local_only_benchmark,
    test_run_row_benchmark_full_uses_sweep_training_contract_for_registration,
    test_run_row_reuse_train_artifact_rejects_row_contract_drift,
    test_run_row_benchmark_full_without_reuse_fails_lazily_when_prior_dump_is_missing,
    test_run_row_reuse_only_skips_fresh_nanotabpfn_helper_when_no_local_reuse_exists,
    test_run_row_reuses_prior_completed_sweep_row_curve_before_bootstrapping_helper,
    test_run_row_reuses_prior_completed_sweep_row_error_before_bootstrapping_helper,
)
